export const API = {
    login: 'auth/login',
    register: 'auth/register',
    oyunlar: 'matches',
    oyunDetail: 'matches/:id',
    oyunlarArxivi: 'matches/archive',
    canliOyunlar: 'matches/live',
    oyuncular: 'players',
    oyuncuDetail: 'players/:id',
    xeberler: 'NewsArticles',     
    xeberDetail: 'NewsArticles/:id', 
    mehsullar: 'products',
    mehsulDetail: 'products/:id',
    vakansiyalar: 'vacancies',
    vakansiyaDetail: 'vacancies/:id',
    vakansiyaApply: 'vacancies/:id/apply',
    nailiyyetler: 'achievements',
    forum: 'forum/categories',
    forumCategory: 'forum/categories/:id',
};